name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.15"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Tests
        run: |
          go test -cover ./...
        shell: bash

  formatting:
    name: Go Format
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    
      - name: Check formatting
        run: ./.gha.gofmt.sh
